name: Simple GitHub Action

on:
  push:
    branches:
      - main

jobs:
  echo_message:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "Hello from GitHub Actions!"
